# Site settings
title: Aaron Jones' Resume
description: Aaron Jones' Resume
favicon: /assets/img/portfolio_pic.png
baseurl: https://bigboss424.github.io/jones-resume
url: https://bigboss424.github.io/jones-resume
rss_url: /pages/atom.xml
google_analytics: UA-129028860-7

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Aaron Jones
  title: Web Developer | Business Owner 
  address: California, United States
  email: ajones061392@yahoo.com
  link: https://www.cogswebdevelopmentandhosting.com/
 # weibo:
  github: bigboss424
  linkedin: aaron-jones-4739bb85
  twitter: heeroyuy424
 # gavatar: /assets/img/portfolio_pic.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1: 
      company: Cogs Web Development and Hosting
      location: California, United States
      title: Owner
      started: 2018
      duration: (2018 - Present)
      description: I run a web hosting and development company. Providing services to build, maintain and host websites
                    and web apps for small and medium sized businesses. Helping these businesses with their online
                    presence and marketing to ensure that traffic and customers and driven to their business. 
    - work2:
      company: Equity Publishing 
      location: Washington, United States
      title: Web Developer
      started: 2015
      duration: (2015 - 2016)
      description: Managed Joomla for the company.
                     Built a webpage magazine for the company and respective clients.
                     Managed Web Hosting Maintenance.
    - work3:
      company: Walla Walla University
      location: Washington, United States
      title: Junior System Administrator
      started: 2009
      duration: (2010 - 2011)
      description: Managed and Maintained the Computer Science Department's Computer Lab. Learned how to maintain and manage various 
                   Linux servers and how to utilize them for the Computer Lab. Worked with the Computer Science Department Chair with 
                   numerous projects and tasks. 
  educationHistory:
    - education1:
      organization: Western Governors Univesity
      location: Online
      degree: Bachelor in Science
      major: Computer Science, Software Engineering
      started: 2019
      duration: (2019 - 2022)
      description: Studying Computer Science and other related material. 
      
    - education2:
      organization: California State University, Los Angeles
      location: Los Angeles
      degree: Bachelor in Science
      major: Computer Science, Software Engineering
      started: 2017
      duration: (2017 - 2018)
      description: Studying Computer Science and other related material. Learning to implement course material into everyday
                    development. 
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: Spanish
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 85%
    - skill2:
      name: C++
      percentage: 45%
    - skill3:
      name: JavaScript
      percentage: 50%
    - skill4:
      name: Angular
      percentage: 25%
    - skill5:
      name: Java
      percentage: 65%
    - skill6:
      name: PHP
      percentage: 30%
    - skill8:
      name: Python
      percentage: 10%
    - skill9:
      name: Vue.js
      percentage: 15%
    - skill10:
      name: React.js
      percentage: 20%
    - skill11:
      name: Bash
      percentage: 50%
    
    

